name: update-live-stream
on:
  schedule:
   - cron: '*/5 14-16 * * *'  # Every 5 minutes from 9AM - 11AM EST
   - cron: '0 13-23,00-01 * * *'  # Every 1 hour from 8AM to 8PM EST
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://first-reformed-church.vercel.app/api/update-video' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
